//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoCarDriveBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvtoCarDriveBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить автомобиль.
        /// </summary>
        public static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить отзыв.
        /// </summary>
        public static string AddFeedback {
            get {
                return ResourceManager.GetString("AddFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить нового админа.
        /// </summary>
        public static string AddNewAdmin {
            get {
                return ResourceManager.GetString("AddNewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить идентификатор.
        /// </summary>
        public static string AddNewId {
            get {
                return ResourceManager.GetString("AddNewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой идентификтор уже добавлен.
        /// </summary>
        public static string AdminAlreadyExists {
            get {
                return ResourceManager.GetString("AdminAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор отсутсвует в списке.
        /// </summary>
        public static string AdminAlreadyRemoved {
            get {
                return ResourceManager.GetString("AdminAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый админ добавлен!.
        /// </summary>
        public static string AdminWasAdded {
            get {
                return ResourceManager.GetString("AdminWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор удален.
        /// </summary>
        public static string AdminWasRemoved {
            get {
                return ResourceManager.GetString("AdminWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список идентификаторов:.
        /// </summary>
        public static string AvailableAdmins {
            get {
                return ResourceManager.GetString("AvailableAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вернулись в предыдущее меню.
        /// </summary>
        public static string BackMessage {
            get {
                return ResourceManager.GetString("BackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиля нету в списке.
        /// </summary>
        public static string CarAlreadyRemoved {
            get {
                return ResourceManager.GetString("CarAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобили.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль успешно добавлен.
        /// </summary>
        public static string CarWasAdded {
            get {
                return ResourceManager.GetString("CarWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автомобиль успешн удален.
        /// </summary>
        public static string CarWasRemoved {
            get {
                return ResourceManager.GetString("CarWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить автомобиль.
        /// </summary>
        public static string ChangeCar {
            get {
                return ResourceManager.GetString("ChangeCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить описание бота.
        /// </summary>
        public static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить название бота.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите информацию об автомобиле.
        /// </summary>
        public static string EnterCarInfo {
            get {
                return ResourceManager.GetString("EnterCarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите идентификатор для удаления.
        /// </summary>
        public static string EnterTheIdForRemoving {
            get {
                return ResourceManager.GetString("EnterTheIdForRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите идентификатор.
        /// </summary>
        public static string EnterTheNewId {
            get {
                return ResourceManager.GetString("EnterTheNewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ввод.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разработке.
        /// </summary>
        public static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация добавлена.
        /// </summary>
        public static string InfoWasAdded {
            get {
                return ResourceManager.GetString("InfoWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список админов.
        /// </summary>
        public static string ListOfAdmins {
            get {
                return ResourceManager.GetString("ListOfAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | The {1} has been sended | User : {2}; Id : {3};.
        /// </summary>
        public static string MessageForLogger {
            get {
                return ResourceManager.GetString("MessageForLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад некуда.
        /// </summary>
        public static string NowhereBack {
            get {
                return ResourceManager.GetString("NowhereBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправил фотографии.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать админа.
        /// </summary>
        public static string RemoveAdmin {
            get {
                return ResourceManager.GetString("RemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать автомобиль.
        /// </summary>
        public static string RemoveCar {
            get {
                return ResourceManager.GetString("RemoveCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы  администратор этого бота.
        /// </summary>
        public static string StartAdminMessage {
            get {
                return ResourceManager.GetString("StartAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | The start message has been sended | User : {1}; Id : {2};.
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денис Сергеевич
        ///Пригон авто из Европы 🇪🇺 и Грузии 🇬🇪 
        ///Ссылка на петицию : 🔜goo.su/1nOk
        ///Консультации по номеру телефона
        ///+380939349912.
        /// </summary>
        public static string StartUserMessage {
            get {
                return ResourceManager.GetString("StartUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто в наличии.
        /// </summary>
        public static string StockCars {
            get {
                return ResourceManager.GetString("StockCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1086801118:AAHLeXeRbILocram22nEf3GEC6u2viIBghY.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто под ключ.
        /// </summary>
        public static string TurnkeyAutos {
            get {
                return ResourceManager.GetString("TurnkeyAutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню клиента.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
    }
}
